#!/usr/bin/perl

use strict;
use warnings;
use File::Copy;

open(BASE, "_base.html");

my $onpre = 0;

my $HTML_START;
my $HTML_END;

while (<BASE>) {
  my $line = $_;
  if($line =~ m/SPLIT HERE/) {
    $onpre = 1;
  } else {
    if($onpre == 0) {
      $HTML_START .= $line;
    } else {
      $HTML_END .= $line;
    }
  }
}

close(BASE);
my $root = '..';

sub create_static { my ($file, $contents) = @_;

  open(FILE, ">$root/$file") or die $!;
  print FILE $HTML_START;
  print FILE $contents;
  print FILE $HTML_END;
  close(FILE);
}

sub process_posts { my ($dir) = @_;
  opendir(DIR, "./$dir") or die $!;

  mkdir "$root/$dir";

  my @index;

  while (my $file = readdir(DIR)) {
      next if $file =~ m/^\./;
      mkdir "$root/$dir/$file";
      print "\t- $file\n";


      open(ARTICLE, "./$dir/$file/article.html") or die $!;
      my @lines = <ARTICLE>;
      my $article = join '', @lines;
      close(ARTICLE);

      my $cover = "";
      my $cover_class = "no-cover";
      if (-e "./$dir/$file/cover.jpg") {
        $cover = "<figure style=\"background-image: url('/$dir/$file/cover.jpg')\" ></figure>";
        $cover_class = "with-cover";
        copy("./$dir/$file/cover.jpg", "$root/$dir/$file/cover.jpg") or die $!;
      }

      my @article_bits = split /\[\[MORE\]\]/, $article;
      my $index_article = $article_bits[0];
      $article = join '', @article_bits;

      my $readmore_link = "";
      if(scalar @article_bits == 2) {
        $readmore_link = "<a class=\"read-more-link\" href=\"/$dir/$file/\">Read More &rarr;</a>";
      }

      $index_article = "<article class=\"index-article $cover_class\">\n$cover\n$index_article\n$readmore_link\n</article>\n";
      push @index, $index_article;
      
      my $main_article = "<article class=\"main-article\">\n$cover\n$article\n</article>\n";

      create_static("$dir/$file/index.html", $main_article);

  }

  my $index_full = join '', @index;

  create_static("$dir/index.html", $index_full);
}

sub wrap_static { my ($file) = @_;
  open(FILE, "./$file") or die $!;
  my @lines = <FILE>;
  my $file_contents = join '', @lines;
  close(FILE);

  create_static($file, $file_contents);
}

my @folders = map { chomp; $_ } `find * -maxdepth 0 ! -path . -type d  -print`;

print "FOLDERS\n";
foreach my $folder (@folders) {
  print "- $folder\n";
  process_posts($folder);
}

print "FILES\n";
my @files = map { chomp; $_ } `find * -maxdepth 0 ! -path . -type f -name '[^_]*.html' -print`;
foreach my $file (@files) {
  print "- $file\n";
  wrap_static("$file");
}

`yuicompressor index.css -o $root/index.css`;
`chmod 755 -R $root`;
