#!/usr/bin/perl

use strict;
use warnings;
use File::Copy;
use Time::Local;
use DateTime;
use File::Copy::Recursive qw(dircopy);
use File::Slurp;

open(BASE, "_base.html");

my $onpre = 0;

my $HTML_START;
my $HTML_END;

while (<BASE>) {
  my $line = $_;
  if($line =~ m/SPLIT HERE/) {
    $onpre = 1;
  } else {
    if($onpre == 0) {
      $HTML_START .= $line;
    } else {
      $HTML_END .= $line;
    }
  }
}

close(BASE);
my $root = '..';
my $page_len = 8;

open(TWITTER, "./_twitter.html") or die $!;
my @_twitterlines = <TWITTER>;
my $twitter = join '', @_twitterlines;
close(TWITTER);

sub create_static($$;$) { my ($file, $contents, $title) = @_;

  open(FILE, ">$root/$file") or die $!;
  if($title) {
    my $HTML_START_TMP = $HTML_START;
    $HTML_START_TMP =~ s|<title>.+</title>|<title>$title - Blackle Mori</title>|;
    print FILE $HTML_START_TMP;
  } else {
    print FILE $HTML_START;
  }
  print FILE $contents;
  print FILE $HTML_END;
  close(FILE);
}

sub friendlydate { my ($time) = @_;
  $time =~ m/(\d+)-(\d+)-(\d+)/;

  $time = DateTime->new(
      year      => $1,
      month     => $2,
      day       => $3,
      time_zone => 'America/Toronto',
  );
  
  return $time->strftime("Posted on %a %b %e, %Y by Isabelle Knott")
}

sub process_posts { my ($dir) = @_;
  opendir(DIR, "./$dir") or die $!;
  my $indexgoodname = ucfirst($dir);

  mkdir "$root/$dir";

  my @index;

  my $post_num = 0;
  while (my $file = readdir(DIR)) {
      next if $file =~ m/^[\._]/;
      mkdir "$root/$dir/$file";
      print "\t- $file\n";




      open(ARTICLE, "./$dir/$file/article.html") or die $!;
      my @lines = <ARTICLE>;
      my $article = join '', @lines;
      close(ARTICLE);


      unless($dir =~ m/links/) {
        $article =~ s/datetime="(.+)">/"datetime=\"".$1."\">".friendlydate($1)/e;
      } else {
        $article =~ s/<time/<time class="hidden"/;
      }

      my $cover = "";
      my $cover_class = "no-cover";
      if (-e "./$dir/$file/cover.jpg") {
        $cover = "<figure style=\"background-image: url('/$dir/$file/cover.jpg')\" ></figure>";
        $cover_class = "with-cover";
        copy("./$dir/$file/cover.jpg", "$root/$dir/$file/cover.jpg") or die $!;
      }

      if (-e "./$dir/$file/img") {
        dircopy("./$dir/$file/img", "$root/$dir/$file/img") or die $!;
      }

      my @article_bits = split /\[\[MORE\]\]/, $article;
      my $index_article = $article_bits[0];
      $article = join '<hr/>', @article_bits;

      my $readmore_link = "";
      unless($dir =~ m/links/) {
        $readmore_link = "<a class=\"read-more-link\" href=\"/$dir/$file/\"><span>Permalink</span></a>";
        if(scalar @article_bits == 2) {
          $readmore_link = "<a class=\"read-more-link\" href=\"/$dir/$file/\"><span>Read More &rarr;</span></a>";
        }
      }

      $index_article = "<article id=\"$file\" class=\"index-article $cover_class\">\n$cover\n$index_article\n$readmore_link\n</article>\n";
      push @index, $index_article;

      # my $go_back_url = "/$dir/#$file";
      # if($post_num >= $page_len) {
      #   my $back_post = int($post_num/$page_len)+1;
      #   $go_back_url = "/$dir/page/$back_post/#$file";
      # }
      
      my $main_article = "<article class=\"main-article\">\n$cover\n$article\n</article>\n";

      unless($dir =~ m/links/) {
        $article =~ m/<h2>([^<]+)<\/h2>/;
        my $title = $1;
        $main_article =~ s|</article>|$twitter</article>|;
        if($title) {
          create_static("$dir/$file/index.html", $main_article, $title);
        } else {
          create_static("$dir/$file/index.html", $main_article);
        }
      }
      $post_num++;
  }

  @index = sort {
    #sort by dates
    $a =~ m/datetime="(\d+)-(\d+)-(\d+)">/;
    my $at = scalar timegm(0,0,0,$3,$2-1,$1);
    $b =~ m/datetime="(\d+)-(\d+)-(\d+)">/;
    my $bt = scalar timegm(0,0,0,$3,$2-1,$1);
    $bt <=> $at;
  }@index;

  if(scalar @index <= $page_len) {
    my $index_full = join '', @index;
    create_static("$dir/index.html", $index_full, $indexgoodname);
  } else {
    mkdir "$root/$dir/page";

    my @pagearray;
    
    while (my @page = splice @index, 0, $page_len) {
      push @pagearray, (join '', @page);
    }

    create_static("$dir/index.html", $pagearray[0]."\n<nav>\n<a class=\"next\" href=\"/$dir/page/2/\"><span>Next</span></a>\n<div class=\"clearfix\"></div>\n</nav>\n", $indexgoodname);

    for(my $pagenum = 2; $pagenum < scalar @pagearray + 1; $pagenum++){
      mkdir "$root/$dir/page/$pagenum";
      my $prev = $pagenum - 1;
      my $next = $pagenum + 1;
      my $prev_button = "";
      if($prev == 1) {
        $prev_button = "<a class=\"back\" href=\"/$dir/\"><span>Back</span></a>";
      } else {
        $prev_button = "<a class=\"back\" href=\"/$dir/page/$prev/\"><span>Back</span></a>";
      }
      my $next_button = "";
      if($next == scalar @pagearray) {
        $next_button = "<a class=\"next\" href=\"/$dir/page/$next/\"><span>Next</span></a>";
      }
      create_static("$dir/page/$pagenum/index.html", $pagearray[$pagenum-1]."\n<nav>\n$prev_button\n$next_button\n<div class=\"clearfix\"></div>\n</nav>\n", $indexgoodname);

    }
  }



}

sub wrap_static { my ($file) = @_;
  open(FILE, "./$file") or die $!;
  my @lines = <FILE>;
  my $file_contents = join '', @lines;
  close(FILE);

  create_static($file, $file_contents);
}

my @folders = map { chomp; $_ } `find * -maxdepth 0 ! -path . -type d  -print`;

print "FOLDERS\n";
foreach my $folder (@folders) {
  print "- $folder\n";
  process_posts($folder);
}

print "FILES\n";
my @files = map { chomp; $_ } `find * -maxdepth 0 ! -path . -type f -name '[^_]*.html' -print`;
foreach my $file (@files) {
  print "- $file\n";
  wrap_static("$file");
}

`cat index.css | cssmin > $root/index.css`;
`cat print.css | cssmin > $root/print.css`;
`chmod 755 -R $root`;

chdir($root) or die "$!";
`./_create_sitemap.sh`
